### ISSUE TITLE
When I delete today's recommended restaurant the recommendations page breaks

### ISSUE THREAD

**Issue by joeunrue** [matt-may/wfl#1]
I was recommended to eat at Bart's Burgers. I wanted to see what would happen if I deleted the restaurant, so I did. And the page broke. :-(

**Comment by mzxrai** [comment]
Nice catch! https://github.com/matt-may/wfl/commit/f0513f62959c90f2074b2b75c79c2a2f44ef0add should fix this issue. I added `dependent: destroy`, so that when a restaurant is deleted, its recommendations are also deleted.

**Comment by joeunrue** [comment]
Awesome, thanks.
